build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  IMGAUG_NO_CV2_INSTALLED_CHECK: 'TRUE'

  matrix:
    - PYTHON: 'C:\Python35-x64'
      PYTORCH_WHEEL: 'https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp35-cp35m-win_amd64.whl'
    - PYTHON: 'C:\Python36-x64'
      PYTORCH_WHEEL: 'https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp36-cp36m-win_amd64.whl'
    - PYTHON: 'C:\Python37-x64'
      PYTORCH_WHEEL: 'https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-win_amd64.whl'

install:
  - '%PYTHON%\python.exe -m pip install -U pip wheel setuptools'
  - 'if defined PYTORCH_WHEEL %PYTHON%\python.exe -m pip install %PYTORCH_WHEEL% torchvision'
  - '%PYTHON%\python.exe -m pip install .[tests]'
  - '%PYTHON%\python.exe -m pip install "pydocstyle<4.0.0" flake8 flake8-docstrings'

test_script:
  - '%PYTHON%\python.exe -m pytest'
  - '%PYTHON%\python.exe -m flake8'
