language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - IMGAUG_NO_CV2_INSTALLED_CHECK=TRUE
    - TEST_MODE=DEFAULT

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7
      env: TEST_MODE=DOCS
    - python: 3.7
      env: TEST_MODE=BLACK
    - python: 3.7
      env: TEST_MODE=SPHINX

install:
- pip install --upgrade pip pytest
- pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
- if [[ "$TEST_MODE" == "DOCS" ]]; then pip install .; fi
- if [[ "$TEST_MODE" == "BLACK" ]]; then pip install black==19.3b0; fi
- if [[ "$TEST_MODE" == "SPHINX" ]]; then pip install -r docs/requirements.txt; fi
- if [[ "$TEST_MODE" == "DEFAULT" ]] || [[ "$TEST_MODE" == "SPHINX" ]]; then pip install .[tests]; fi
- if [[ "$TEST_MODE" == "DEFAULT" ]]; then pip install "pydocstyle<4.0.0" flake8 flake8-docstrings; fi

script:
  - if [[ "$TEST_MODE" == "DOCS" ]]; then python tools/make_transforms_docs.py check README.md; fi
  - if [[ "$TEST_MODE" == "BLACK" ]]; then black --config=black.toml --check .; fi
  - if [[ "$TEST_MODE" == "SPHINX" ]]; then sphinx-build -b html docs /tmp/_docs_build; fi
  - if [[ "$TEST_MODE" == "DEFAULT" ]]; then pytest; fi
  - if [[ "$TEST_MODE" == "DEFAULT" ]]; then flake8; fi
